spring.application.name=web

# Conexion a PostgreSQL: jdbc:postgresql://<servidor>:<puerto>/<base de datos>
spring.jpa.database=POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/elcasarcd
spring.datasource.username=elcasar
spring.datasource.password=123456
#se genra por defecto el esqeuam de la bbdd
spring.jpa.generate-ddl=true


# Hibernate compara las clases @Entity con las tablas y las crea/ajusta al arrancar
spring.jpa.hibernate.ddl-auto=update

# Muestra en consola el SQL que Hibernate ejecuta (muy util para aprender)
spring.jpa.show-sql=true
